const spots = [
  {
    title: "IStanbul,Turkey",
    img: "https://images.unsplash.com/photo-1490079397423-a3931fd75940?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=928&q=80",
    price: "$1200",
    description:
      "Istanbul is the largest city in Turkey, constituting the country's economic, cultural, and historical heart. Its commercial and historical centre lies in the European part of Eurasia, while about a third of its population lives in the Asian part. With a population of 14.1 million, the city forms the largest urban agglomeration in Europe as well as the largest in the Middle East, and the sixth-largest city proper in the world. Istanbul's vast area of 5,343 square kilometres is coterminous with Istanbul Province, of which the city is the administrative capital. Istanbul is a transcontinental city, straddling the Bosphorus strait in northwestern Turkey between the Sea of Marmara and the Black Sea.Founded on the Sarayburnu promontory around 660 BC as Byzantium, the city now known as Istanbul developed to become one of the most significant cities in history. For nearly sixteen centuries following its reestablishment as Constantinople in 330 AD, it served as the capital of four empires: the Roman Empire (330–395), the Byzantine Empire (395-1204 and 1261-1453), the Latin Empire (1204-1261), and the Ottoman Empire (1453-1922). It was instrumental in the advancement of Christianity during Roman and Byzantine times, before the Ottomans conquered the city in 1453 and transformed it into an Islamic stronghold and the seat of the last caliphate.Istanbul's strategic position along the historic Silk Road, rail networks to Europe and the Middle East.",
  },
  {
    title: "Longs Peak, The USA",
    img: "https://images.unsplash.com/photo-1579271223449-882e37c1baf3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80",
    price: "$1500",
    description:
      "Longs Peak, mountain peak in the Front Range of the Rocky Mountains, Boulder county, north-central Colorado, U.S. It is the highest peak (14,259 feet [4,346 metres]) in Rocky Mountain National Park and the northernmost “fourteener” in Colorado. It was named in honour of Major Stephen H. Long, an American army officer and explorer who encountered it in 1820. Several hiking trails lead to the summit.Front Range, easternmost section of the Southern Rocky Mountains in the west-central United States. It extends about 300 miles (500 km) south-southeastward from near Casper in southeastern Wyoming to Fremont county in south-central Colorado. The Front Range is 40 to 50 miles (65 to 80 km) wide and includes the Laramie and Medicine Bow mountains; the Sangre de Cristo Mountains are usually regarded as a southern extension.Lying largely within conservation areas, the Front Range constitutes the whole of Rocky Mountain National Park and occupies portions of Pike, Arapaho, Routt, Roosevelt, and Medicine Bow national forests. The range is known for its variety of minerals and its recreational appeal, and it serves as a source region for headstreams of the Cache la Poudre and Colorado rivers",
  },
  {
    title: "Great Wall of China, China",
    img: "https://images.unsplash.com/photo-1508804052814-cd3ba865a116?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1470&q=80",
    price: "$1900",
    description:
      "The Great Wall of China (traditional Chinese: 萬里長城; simplified Chinese: 万里长城; pinyin: Wànlǐ Chángchéng) is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe. Several walls were built from as early as the 7th century BC,[2] with selective stretches later joined together by Qin Shi Huang (220–206 BC), the first emperor of China. Little of the Qin wall remains.[3] Later on, many successive dynasties built and maintained multiple stretches of border walls. The best-known sections of the wall were built by the Ming dynasty (1368–1644).Apart from defense, other purposes of the Great Wall have included border controls, allowing the imposition of duties on goods transported along the Silk Road, regulation or encouragement of trade and the control of immigration and emigration.[4] Furthermore, the defensive characteristics of the Great Wall were enhanced by the construction of watchtowers, troop barracks, garrison stations, signaling capabilities through the means of smoke or fire.",
  },
  {
    title: "Swiss Apls,Switzerland",
    img: "https://images.unsplash.com/photo-1559208944-221ef1b9d9e3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=876&q=80",
    price: "$2200",
    description:
      "The Alpine region of Switzerland, conventionally referred to as the Swiss Alps (German: Schweizer Alpen, French: Alpes suisses, Italian: Alpi svizzere, Romansh: Alps svizras), represents a major natural feature of the country and is, along with the Swiss Plateau and the Swiss portion of the Jura Mountains, one of its three main physiographic regions. The Swiss Alps extend over both the Western Alps and the Eastern Alps, encompassing an area sometimes called Central Alps.[1] While the northern ranges from the Bernese Alps to the Appenzell Alps are entirely in Switzerland, the southern ranges from the Mont Blanc massif to the Bernina massif are shared with other countries such as France, Italy, Austria and Liechtenstein.The Swiss Alps comprise almost all the highest mountains of the Alps, such as Dufourspitze (4,634 m), the Dom (4,545 m), the Liskamm (4,527 m), the Weisshorn (4,506 m) and the Matterhorn (4,478 m). The other following major summits can be found in this list of mountains of Switzerland.Since the Middle Ages, transit across the Alps played an important role in history. The region north of St Gotthard Pass became the nucleus of the Swiss Confederacy in the early 14th century.",
  },
  {
    title: "Cox's Bazar,Chittagong",
    img: "https://images.unsplash.com/photo-1495546992359-94a48035efca?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80",
    price: "$1000",
    description:
      "From the early 9th century the greater Chittagong area, including Cox's Bazar, was under the rule of Arakan kings until its conquest by the Mughals in 1666 AD.[4] When the Mughal Prince Shah Shuja was passing through the hilly terrain of the present-day Cox's Bazar on his way to Arakan, he was attracted to its scenic and captivating beauty. He commanded his forces to camp there. His retinue of one thousand palanquins stopped there for some time. A place named Dulahazara, meaning still exists in the area. After the Mughals, the place came under the control of the Tipras and the Arakanese, followed by the Portuguese and then the British.The name Cox's Bazar originated from the name of a British East India Company officer, Captain Hiram Cox, who was appointed as the Superintendent of Palonki (today's Cox's Bazar) outpost. He succeeded Warren Hastings, who became the Governor of Bengal following the British East India Company Act in 1773. Cox embarked upon the task of rehabilitation and settlement of the Arakanese refugees in the area.[5] He rehabilitated many refugees in the area, but died in 1799 before finishing his work. To commemorate him, a market was established and named after him, called Cox's Bazar. Cox's Bazar was first established in 1854 and became a municipality in 1869.[4]",
  },
  {
    title: "Fiordland, New Zealand",
    img: "https://images.unsplash.com/photo-1553579857-74fb7643a502?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1032&q=80",
    price: "$1600",
    description:
      "Fiordland is a geographic region of New Zealand in the south-western corner of the South Island, comprising the westernmost third of Southland. Most of Fiordland is dominated by the steep sides of the snow-capped Southern Alps, deep lakes, and its steep, glacier-carved and now ocean-flooded western valleys. The name comes from a variant spelling of the Scandinavian word for this type of steep valley,  The area of Fiordland is dominated by, and very roughly coterminous with, Fiordland National Park, New Zealand's largest National Park.Due to the often steep terrain and high amount of rainfall supporting dense vegetation, the interior of the Fiordland region is largely inaccessible. As a result, Fiordland was never subjected to notable logging operations, and even attempts at whaling, seal hunting, and mining were on a small scale and short-lived, partly also because of the challenging weather.[1] Today, Fiordland contains by far the greatest extent of unmodified vegetation in New Zealand and significant populations of endemic plants and threatened animals, in some cases the only remaining wild populations.iordland features a number of fiords, which in this area are typically named sounds, reflecting the fact that sometimes fiords are considered to be a type of a narrow sound.",
  },
];
